"""empty message

Revision ID: 0e39d625df4e
Revises: 680d64f69ca2
Create Date: 2023-10-21 20:04:45.801537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e39d625df4e'
down_revision = '680d64f69ca2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enrollment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], name='fk_enrollment_event'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_enrollment_user'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('enrollment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_enrollment_date'), ['date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_enrollment_date'))

    op.drop_table('enrollment')
    # ### end Alembic commands ###
