"""modifying event

Revision ID: 680d64f69ca2
Revises: 7db56d92858c
Create Date: 2023-10-18 20:10:39.694602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '680d64f69ca2'
down_revision = '7db56d92858c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_event_user', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_constraint('fk_event_user', type_='foreignkey')

    # ### end Alembic commands ###
